name: 'sectoral'
version: '1.0.0'
config-version: 2

profile: 'sectoral'

model-paths: ['models']
seed-paths: ['seeds']
test-paths: ['tests']
macro-paths: ['macros']
snapshot-paths: ['snapshots']

models:
  sectoral:
    +materialized: view

    staging:
      +schema: 'staging'
      +tags: ['staging']

    intermediate:
      +schema: 'intermediate'
      +tags: ['intermediate']

    marts:
      +schema: 'marts'
      +tags: ['marts']
