[project]
name = "sectoral"
version = "0.1.0"
description = "Sectoral: financial sectors analysis"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "yfinance",
    "pandas",
    "numpy"
]
